/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsEnum,
  ValidateNested,
  IsDate,
} from "class-validator";
import { EnumGameGenre } from "./EnumGameGenre";
import { LeaderboardCreateNestedManyWithoutGamesInput } from "./LeaderboardCreateNestedManyWithoutGamesInput";
import { Type } from "class-transformer";
import { SessionCreateNestedManyWithoutGamesInput } from "./SessionCreateNestedManyWithoutGamesInput";

@InputType()
class GameCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumGameGenre,
  })
  @IsEnum(EnumGameGenre)
  @IsOptional()
  @Field(() => EnumGameGenre, {
    nullable: true,
  })
  genre?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => LeaderboardCreateNestedManyWithoutGamesInput,
  })
  @ValidateNested()
  @Type(() => LeaderboardCreateNestedManyWithoutGamesInput)
  @IsOptional()
  @Field(() => LeaderboardCreateNestedManyWithoutGamesInput, {
    nullable: true,
  })
  leaderboards?: LeaderboardCreateNestedManyWithoutGamesInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  releaseDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutGamesInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutGamesInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutGamesInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutGamesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { GameCreateInput as GameCreateInput };
